# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-24 07:49
from __future__ import unicode_literals

import apiservice.utils.uuid
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.UUIDField(default=apiservice.utils.uuid.UUIDTools.uuid1_hex, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('allow_comment', models.BooleanField(default=True, verbose_name='允许评论')),
                ('status', models.IntegerField(blank=True, choices=[(0, 'draft'), (1, 'published'), (2, 'deleted')], default=0, verbose_name='状态')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='生成时间')),
                ('read', models.PositiveIntegerField(default=0, verbose_name='阅览量')),
            ],
            options={
                'verbose_name': '文章',
                'verbose_name_plural': '文章列表',
            },
        ),
        migrations.CreateModel(
            name='ArticleTagShip',
            fields=[
                ('id', models.UUIDField(default=apiservice.utils.uuid.UUIDTools.uuid1_hex, editable=False, primary_key=True, serialize=False)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_ship', to='vbblog.Article')),
            ],
            options={
                'verbose_name': '文章标签映射',
                'verbose_name_plural': '文章标签映射',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=apiservice.utils.uuid.UUIDTools.uuid1_hex, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30, verbose_name='名称')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='生成时间')),
            ],
            options={
                'verbose_name': '文章分类',
                'verbose_name_plural': '分类列表',
            },
        ),
        migrations.CreateModel(
            name='SystemMeta',
            fields=[
                ('id', models.UUIDField(default=apiservice.utils.uuid.UUIDTools.uuid1_hex, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=20, verbose_name='配置键')),
                ('value', models.CharField(max_length=50, verbose_name='配置值')),
            ],
            options={
                'verbose_name': '系统元数据',
                'verbose_name_plural': '系统元数据',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.UUIDField(default=apiservice.utils.uuid.UUIDTools.uuid1_hex, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='名称')),
                ('article', models.ManyToManyField(related_name='article_tag', through='vbblog.ArticleTagShip', to='vbblog.Article')),
            ],
            options={
                'verbose_name': '文章标签',
                'verbose_name_plural': '标签列表',
            },
        ),
        migrations.AddField(
            model_name='articletagship',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag_ship', to='vbblog.Tag'),
        ),
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category_article', to='vbblog.Category'),
        ),
        migrations.AddField(
            model_name='article',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_article', to=settings.AUTH_USER_MODEL),
        ),
    ]
